version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - gofmt
    - goimports
    - misspell
    - prealloc
    - unconvert
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic

linters-settings:
  govet:
    enable:
      - shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance